spring.application.name=Currencies
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
currencybeacon.api.key=${CURRENCYBEACON_API_KEY}
currencybeacon.api.root=${CURRENCYBEACON_API_ROOT}
local.timezone=${LOCAL_TIMEZONE}
springdoc.swagger-ui.path=/docs

spring.jpa.hibernate.ddl-auto=update
logging.file.name=logs/app.log
logging.logback.rollingpolicy.max-file-size=3MB
logging.logback.rollingpolicy.max-history=2
logging.logback.rollingpolicy.total-size-cap=10MB